---
- name: Install Apache HTTP Server
  apt: name=apache2 state=present

- name: Enable `mod_rewrite`
  command: a2enmod rewrite

- name: Enable `mod_ssl`
  command: a2enmod ssl

- name: Enable `mod_headers`
  command: a2enmod headers

- name: Create `~/etc/ssl` directory
  file: path=/home/vagrant/etc/ssl state=directory

- name: Copy SSL certificate
  template:
    src=apache/ssl/dummy.crt
    dest=/home/vagrant/etc/ssl/dummy.crt

- name: Copy SSL key
  template:
    src=apache/ssl/dummy.key
    dest=/home/vagrant/etc/ssl/dummy.key

- name: Remove default Virtual Host configuration
  file:
    path=/etc/apache2/sites-enabled/000-default.conf
    state=absent

- name: Remove default SSL Virtual Host configuration
  file:
    path=/etc/apache2/sites-enabled/default-ssl.conf
    state=absent

- name: Copy Virtual Host configuration
  template:
    src=apache/vhost.conf.j2
    dest=/etc/apache2/sites-available/vagrant.conf

- name: Enable Virtual Host configuration
  file:
    src=/etc/apache2/sites-available/vagrant.conf
    dest=/etc/apache2/sites-enabled/vagrant.conf
    state=link
  notify:
    - Reload Apache HTTP Server