- name: Install Apache Solr
  command: "{{ item }}"
  with_items:
    - wget http://archive.apache.org/dist/lucene/solr/5.5.0/solr-5.5.0.tgz
    - tar xvf solr-5.5.0.tgz
    - ./solr-5.5.0/bin/install_solr_service.sh solr-5.5.0.tgz
    - rm solr-5.5.0.tgz
    - rm -rf solr-5.5.0